name: Build Blog with Hugo

on:
  push:
    branches:
     - main  # Set a branch to deploy
     
  # Allows to run the workflow manually
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Configure AWS Credentials (Assume Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::158047604812:role/GitHubActions  # Replace with your AWS Role ARN
          aws-region: eu-west-1  # Adjust to your AWS region

      - name: Verify AWS Authentication
        run: aws sts get-caller-identity  # Shows assumed role details

      - name: Sync public folder dir with S3 bucket
        run: aws s3 sync public/ s3://tech-blog-bootcamp/tech_blog --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id EMBJIYXFZ0H6R --paths "/*"
